import {
  BadgeCheck,
  Box,
  FileSearch,
  FolderTree,
  Hammer,
  LayoutDashboard,
  Library,
  Server,
  Settings,
  ShieldCheck,
  Wrench,
} from 'lucide-react'

export const navItems = [
  { to: '/', label: 'Dashboard', title: 'Dashboard', description: 'KPIs, stats, and recent verification runs', icon: LayoutDashboard },
  { to: '/verify', label: 'Verify', title: 'Verify', description: 'Submit artifacts or manifests for verification', icon: BadgeCheck },
  { to: '/runs', label: 'Runs', title: 'Runs', description: 'View all verification runs and their status', icon: FileSearch },
  { to: '/artifacts', label: 'Artifacts', title: 'Artifacts', description: 'Browse evidence files from verification runs', icon: FolderTree },
  { to: '/jobs-api', label: 'Jobs API', title: 'Runtime Jobs', description: 'Submit jobs, check status, get evidence, replay', icon: Server },
  { to: '/doctor', label: 'Doctor', title: 'Host Doctor', description: 'Check machine capabilities and reproducibility', icon: Wrench },
  { to: '/setup', label: 'Setup', title: 'Setup Planner', description: 'Plan and lock environment configurations', icon: Settings },
  { to: '/route-run', label: 'Route Run', title: 'Route Execution', description: 'Select and run deterministic execution routes', icon: Box },
  { to: '/certify', label: 'Certify', title: 'Certification', description: 'Generate signed certification bundles', icon: ShieldCheck },
  { to: '/conformance', label: 'Conformance', title: 'Conformance & Gates', description: 'Review gate results and conformance reports', icon: BadgeCheck },
  { to: '/api-tools', label: 'API Tools', title: 'API Tools', description: 'Validate signatures and classify API errors', icon: Hammer },
  { to: '/module-explorer', label: 'Explorer', title: 'Module Explorer', description: 'Browse runtime packages and source files', icon: Library },
  { to: '/docs', label: 'Docs', title: 'Documentation', description: 'Guides, tutorials, and API reference', icon: FileSearch },
  { to: '/settings', label: 'Settings', title: 'Settings', description: 'API endpoints, theme, and refresh settings', icon: Settings },
] as const
