import {
  BadgeCheck,
  Box,
  FileSearch,
  FolderTree,
  Hammer,
  LayoutDashboard,
  Library,
  Server,
  Settings,
  ShieldCheck,
  Wrench,
} from 'lucide-react'

export const navItems = [
  { to: '/', label: 'Dashboard', title: 'Dashboard', description: 'Overview of verification system status', icon: LayoutDashboard },
  { to: '/verify', label: 'Verify', title: 'Verify', description: 'Verify models and fixtures for deterministic execution', icon: BadgeCheck },
  { to: '/runs', label: 'Runs', title: 'Runs', description: 'View and manage verification runs', icon: FileSearch },
  { to: '/artifacts', label: 'Artifacts', title: 'Artifacts', description: 'Browse run artifacts and evidence files', icon: FolderTree },
  { to: '/jobs-api', label: 'Jobs API', title: 'Runtime Jobs', description: 'Operate submit, status, evidence, and replay endpoints', icon: Server },
  { to: '/doctor', label: 'Doctor', title: 'Host Doctor', description: 'Inspect machine capabilities and reproducibility risks', icon: Wrench },
  { to: '/setup', label: 'Setup', title: 'Setup Planner', description: 'Plan and lock setup configurations', icon: Settings },
  { to: '/route-run', label: 'Route Run', title: 'Route Execution', description: 'Select deterministic execution routes', icon: Box },
  { to: '/certify', label: 'Certify', title: 'Certification', description: 'Generate certification bundles and signatures', icon: ShieldCheck },
  { to: '/conformance', label: 'Conformance', title: 'Conformance & Gates', description: 'Review conformance reports and verification gates', icon: BadgeCheck },
  { to: '/api-tools', label: 'API Tools', title: 'API Tools', description: 'Validate signatures and classify errors', icon: Hammer },
  { to: '/module-explorer', label: 'Explorer', title: 'Module Explorer', description: 'Navigate runtime subsystems and packages', icon: Library },
  { to: '/docs', label: 'Docs', title: 'Documentation', description: 'Read docs, tutorials, and guides', icon: FileSearch },
  { to: '/settings', label: 'Settings', title: 'Settings', description: 'Configure console preferences', icon: Settings },
] as const
