# Generated by tools/codegen/generate.py; DO NOT EDIT.
# Source: {source_summary}
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

{class_blocks}
