# Generated by tools/codegen/generate.py; DO NOT EDIT.
# Source: {source_summary}
from __future__ import annotations

from typing import Any, Dict

from src.glyphser.error.emit import emit_error

{stub_blocks}
