# Generated by tooling/codegen/generate.py; DO NOT EDIT.
# Source: {source_summary}
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from runtime.glyphser.error.emit import emit_error
from runtime.glyphser.checkpoint.write import save_checkpoint
from runtime.glyphser.checkpoint.restore import restore_checkpoint
from runtime.glyphser.checkpoint.migrate_checkpoint import checkpoint_migrate
from runtime.glyphser.trace.migrate_trace import migrate_trace
from runtime.glyphser.registry.version_create import version_create
from runtime.glyphser.registry.stage_transition import stage_transition
from runtime.glyphser.tracking.run_create import run_create
from runtime.glyphser.tracking.run_start import run_start
from runtime.glyphser.tracking.run_end import run_end
from runtime.glyphser.tracking.metric_log import metric_log
from runtime.glyphser.tracking.artifact_put import artifact_put
from runtime.glyphser.tracking.artifact_get import artifact_get
from runtime.glyphser.tracking.artifact_list import artifact_list
from runtime.glyphser.tracking.artifact_tombstone import artifact_tombstone
from runtime.glyphser.monitor.register import monitor_register
from runtime.glyphser.monitor.emit import monitor_emit
from runtime.glyphser.monitor.drift_compute import drift_compute
from runtime.glyphser.backend.load_driver import load_driver
from runtime.glyphser.dp.apply import dp_apply
from runtime.glyphser.model.forward import forward
from runtime.glyphser.model.model_ir_executor import execute as model_ir_execute
from runtime.glyphser.tmmu.prepare_memory import prepare_memory
from runtime.glyphser.cert.evidence_validate import evidence_validate
from runtime.glyphser.config.migrate_manifest import manifest_migrate
from runtime.glyphser.legacy_import.legacy_framework import legacy_framework_import


def _contract_violation(operator_id: str) -> Dict[str, Any]:
    return {
        "error": emit_error(
            "CONTRACT_VIOLATION",
            "invalid request",
            operator_id=operator_id,
        )
    }


def _primitive_unsupported(operator_id: str) -> Dict[str, Any]:
    return {
        "error": emit_error(
            "PRIMITIVE_UNSUPPORTED",
            "Generated stub not implemented",
            operator_id=operator_id,
            t="placeholder",
            node_id="placeholder",
            instr="placeholder",
            backend_binary_hash="placeholder",
        )
    }

{stub_blocks}
