# Generated by tooling/codegen/generate.py; DO NOT EDIT.
# Source: registry+schemas
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class GlyphserEvidenceMetadataCatalog:
    entries: List[Any]
    generated_at_utc: str
    generator: str
    schema_version: str


@dataclass
class APIInterfaces:
    interface_hash: str
    interfaces: List[Any]
    spec_version: str


@dataclass
class CanonicalCBORProfile:
    float_format: str
    map_key_ordering: str
    simple_values: Optional[List[Any]] = None
    string_normalization: Optional[str] = None
    tag_policy: Optional[str] = None


@dataclass
class DataStructures:
    CheckpointHeader: Dict[str, Any]
    FieldDecl: Dict[str, Any]
    StructDecl: Dict[str, Any]
    TraceErrorRecord: Dict[str, Any]
    TraceIterRecord: Dict[str, Any]
    TraceRunHeader: Dict[str, Any]


@dataclass
class DependencyLockPolicy:
    dependencies_lock_hash: str
    lockfile_hash: str
    artifact_index_hash: Optional[str] = None
    policy_bundle_hash: Optional[str] = None
    runtime_env_hash: Optional[str] = None
    sbom_hash: Optional[str] = None
    toolchain_hash: Optional[str] = None


@dataclass
class DeterminismProfiles:
    determinism_profile_hash: str
    determinism_profile_id: str
    default_compare_policy: Optional[str] = None
    nan_policy: Optional[str] = None
    profile_rules: Optional[Dict[str, Any]] = None
    tolerance_map: Optional[Dict[str, Any]] = None


@dataclass
class DigestCatalog:
    catalog_version: int
    entries: List[Any]


@dataclass
class EnvironmentManifest:
    backend_binary_hash: str
    driver_runtime_fingerprint_hash: str
    runtime_env_hash: str
    arch: Optional[str] = None
    dependencies_lock_hash: Optional[str] = None
    gpu: Optional[str] = None
    os: Optional[str] = None
    toolchain_hash: Optional[str] = None


@dataclass
class GlyphserErrorCodes:
    error_codes: List[Any]


@dataclass
class NormativityLegend:
    tags: List[Any]
    default_rules: Optional[str] = None


@dataclass
class OperatorRegistrySchema:
    allowed_error_codes: List[Any]
    determinism_class: str
    method: str
    operator_id: str
    purity_class: str
    request_schema_digest: str
    required_capabilities: List[Any]
    response_schema_digest: str
    rng_usage: str
    side_effects: List[Any]
    surface: str
    version: str


@dataclass
class RedactionPolicy:
    classification: str
    redaction_mode: str
    transform: str
    redaction_key_id: Optional[str] = None
    redaction_policy_hash: Optional[str] = None


@dataclass
class AuthZCapabilityMatrixL2:
    capabilities: List[Any]
    roles: List[Any]


@dataclass
class CheckpointSchemaL2:
    checkpoint_hash: str
    checkpoint_header_hash: str
    checkpoint_manifest_hash: str
    artifact_index_hash: Optional[str] = None
    backend_binary_hash: Optional[str] = None
    checkpoint_hash_prev: Optional[str] = None
    checkpoint_merkle_root: Optional[str] = None
    data_cursors_hash: Optional[str] = None
    dataset_snapshot_id: Optional[str] = None
    determinism_profile_hash: Optional[str] = None
    dp_accountant_manifest_hash: Optional[str] = None
    dp_accountant_state_hash: Optional[str] = None
    ir_hash: Optional[str] = None
    lineage_root_hash: Optional[str] = None
    manifest_hash: Optional[str] = None
    optimizer_manifest_hash: Optional[str] = None
    optimizer_state_root_hash: Optional[str] = None
    policy_bundle_hash: Optional[str] = None
    rng_state_hash: Optional[str] = None
    sampler_config_hash: Optional[str] = None
    tensors_root_hash: Optional[str] = None
    tmmu_plan_hash: Optional[str] = None
    trace_final_hash: Optional[str] = None
    weights_manifest_hash: Optional[str] = None


@dataclass
class ConfigSchemaL2:
    datasets: Dict[str, Any]
    environment: Dict[str, Any]
    global_batch_size: int
    model: Dict[str, Any]
    optimizer: Dict[str, Any]
    pipeline_stages: List[Any]
    policy_bundle: Dict[str, Any]
    security: Dict[str, Any]
    seed: int
    spec_version: str
    tenant_id: str
    checkpoint_frequency: Optional[int] = None
    custom_operators: Optional[List[Any]] = None
    data: Optional[Dict[str, Any]] = None
    execution_mode: Optional[str] = None
    fingerprint_frequency: Optional[int] = None
    job_priority: Optional[int] = None
    parallelism: Optional[Dict[str, Any]] = None
    policy: Optional[Dict[str, Any]] = None
    schema_mode: Optional[str] = None
    task_type: Optional[str] = None


@dataclass
class DataLineageL2:
    data_access_plan_hash: str
    dataset_snapshot_id: str
    lineage_root_hash: str
    split_hashes: Optional[List[Any]] = None
    transform_chain_hash: Optional[str] = None


@dataclass
class DataNextBatchL2:
    dataset_key: str
    global_batch_size: int
    seed: int
    world_size: int


@dataclass
class DeploymentRunbookL2:
    commands: List[Any]
    environment: str
    runbook_version: str


@dataclass
class DifferentialPrivacyApplyL2:
    accountant: str
    clipping_strategy: str
    delta: float
    epsilon: float


@dataclass
class EvaluationHarnessL2:
    metrics: List[Any]
    thresholds: Optional[Dict[str, Any]] = None


@dataclass
class ExecutionCertificateL2:
    certificate_hash: str
    signed_payload: Dict[str, Any]
    unsigned_metadata: Optional[Dict[str, Any]] = None


@dataclass
class ExperimentTrackingL2:
    checkpoint_hash: str
    created_at: str
    execution_certificate_hash: str
    manifest_hash: str
    replay_token: str
    run_id: str
    status: str
    tenant_id: str
    trace_final_hash: str
    ended_at: Optional[str] = None


@dataclass
class GlyphserKernelV322OSL2:
    execution_mode: Optional[str] = None
    manifest_hash: Optional[str] = None
    replay_token: Optional[str] = None
    run_id: Optional[str] = None


@dataclass
class ModelRegistryL2:
    model_hash: str
    model_id: str


@dataclass
class ModelIRExecutorL2:
    ir_hash: str
    replay_token: str
    outputs: Optional[List[Any]] = None


@dataclass
class MonitoringPolicyL2:
    monitor_policy_hash: str
    policy_gate_hash: str
    baselines: Optional[List[Any]] = None
    metrics: Optional[List[Any]] = None
    monitor_summary_hash: Optional[str] = None
    thresholds: Optional[Dict[str, Any]] = None


@dataclass
class PipelineOrchestratorL2:
    pipeline_stages: List[Any]
    task_type: str
    world_size: int


@dataclass
class ReplayDeterminismL2:
    determinism_profile_hash: str
    kernel_replay_token: str
    replay_token: str
    driver_runtime_fingerprint_hash: Optional[str] = None
    env_manifest_hash: Optional[str] = None
    operator_contracts_root_hash: Optional[str] = None
    policy_bundle_hash: Optional[str] = None
    seed: Optional[int] = None


@dataclass
class RunCommitWALL2:
    record_hash: str
    run_id: str
    wal_seq: int


@dataclass
class SecurityComplianceProfileL2:
    execution_mode: str
    attestation_bundle_hash: Optional[str] = None
    attestation_quote_hash: Optional[str] = None
    measurements_hash: Optional[str] = None
    redaction_mode: Optional[str] = None
    tcb_version: Optional[str] = None
    tee_type: Optional[str] = None
    verification_report_hash: Optional[str] = None


@dataclass
class TMMUAllocationL2:
    allocation_header: Dict[str, Any]
    arena_config: Dict[str, Any]
    ir_hash: str
    replay_token: str
    metrics: Optional[Dict[str, Any]] = None
    tensor_map: Optional[Dict[str, Any]] = None


@dataclass
class TraceSidecarL2:
    error_records: List[Any]
    iter_records: List[Any]
    run_header: Dict[str, Any]
    trace_final_hash: str


@dataclass
class CompatibilityTestMatrixL3:
    cases: List[Any]
    matrix: List[Any]
    status: Optional[str] = None


@dataclass
class ConformanceCIPipelineL3:
    gates: List[Any]
    steps: List[Any]
    artifacts: Optional[List[Any]] = None


@dataclass
class ConformanceHarnessGuideL3:
    commands: List[Any]
    inputs: List[Any]


@dataclass
class CoverageTargetsL3:
    targets: List[Any]
    thresholds: Optional[Dict[str, Any]] = None


@dataclass
class DataContractFuzzingGuideL3:
    fuzz_cases: List[Any]


@dataclass
class FailureInjectionIndexL3:
    scenarios: List[Any]


@dataclass
class FailureInjectionScenariosL3:
    scenarios: List[Any]


@dataclass
class GameDayScenariosL3:
    scenarios: List[Any]


@dataclass
class IntegrationTestMatrixL3:
    cases: List[Any]
    matrix: List[Any]
    status: Optional[str] = None


@dataclass
class GlyphserOperatorErrorVectors:
    operator_id: str
    vectors: List[Any]


@dataclass
class GlyphserOperatorVectors:
    operator_id: str
    vectors: List[Any]


@dataclass
class PerformancePlanL3:
    metrics: List[Any]
    thresholds: Optional[Dict[str, Any]] = None


@dataclass
class ReleaseGatesL3:
    gates: List[Any]
    pass_criteria: Optional[str] = None


@dataclass
class StorageRecoveryTestMatrixL3:
    cases: List[Any]


@dataclass
class TestPlanL3:
    pass_criteria: str
    tests: List[Any]
    coverage: Optional[str] = None


@dataclass
class TestVectorsCatalogL3:
    catalog_version: str
    vectors: List[Any]
    coverage: Optional[str] = None


@dataclass
class APILifecycleAndDeprecationPolicyL4:
    pass


@dataclass
class ArchitectureDecisionsLogL4:
    pass


@dataclass
class ArtifactStoreAdapterGuideL4:
    pass


@dataclass
class BackendAdapterGuideL4:
    pass


@dataclass
class BackendFeatureMatrixL4:
    pass


@dataclass
class BenchmarkEvidenceSpecL4:
    pass


@dataclass
class BrownfieldDeploymentGuideL4:
    pass


@dataclass
class BuildAndCIMatrixL4:
    pass


@dataclass
class CanonicalHashingReferenceL4:
    pass


@dataclass
class ChangeControlPlaybookL4:
    pass


@dataclass
class CLICommandProfilesL4:
    pass


@dataclass
class CodeGenerationMappingL4:
    pass


@dataclass
class CodingStandardsL4:
    pass


@dataclass
class CommandReferenceL4:
    pass


@dataclass
class CommonPitfallsGuideL4:
    pass


@dataclass
class CommunityGovernanceModelL4:
    pass


@dataclass
class ContractsArtifactLifecycleL4:
    pass


@dataclass
class ContributingWorkflowL4:
    pass


@dataclass
class DebuggingPlaybookL4:
    pass


@dataclass
class DeterminismAuditPlaybookL4:
    pass


@dataclass
class DeterminismDebugChecklistL4:
    pass


@dataclass
class DeterministicRNGImplementationGuideL4:
    pass


@dataclass
class DeveloperSetupL4:
    pass


@dataclass
class DeveloperTroubleshootingFAQL4:
    pass


@dataclass
class DisasterRecoveryOperationsRunbookL4:
    pass


@dataclass
class DistributedFailureRecoveryGuideL4:
    pass


@dataclass
class EcosystemExpansionRoadmapL4:
    pass


@dataclass
class EQCCIPolicyL4:
    pass


@dataclass
class EvidenceCatalogL4:
    pass


@dataclass
class ExpansionCatalog041250L4:
    pass


@dataclass
class ExternalInterfaceStandardL4:
    pass


@dataclass
class FixturesAndGoldenDataL4:
    pass


@dataclass
class FormalVerificationRoadmapL4:
    pass


@dataclass
class GentleIntroductionL4:
    pass


@dataclass
class HelloWorldEndToEndExampleL4:
    pass


@dataclass
class ImplementationBacklogL4:
    pass


@dataclass
class ImplementationRoadmapL4:
    pass


@dataclass
class IncidentPostmortemTemplateL4:
    pass


@dataclass
class IndustryProductizationUpgradePlanL4:
    pass


@dataclass
class InteroperabilityStandardsBridgeL4:
    pass


@dataclass
class LocalReplayRunbookL4:
    pass


@dataclass
class MigrationExecutionGuideL4:
    pass


@dataclass
class ModuleScaffoldingGuideL4:
    pass


@dataclass
class OperatorConformanceMatrixL4:
    pass


@dataclass
class OperatorRegistryCBORContractL4:
    pass


@dataclass
class OperatorSDKScaffoldTemplateL4:
    pass


@dataclass
class PRReviewChecklistL4:
    pass


@dataclass
class ProfilingAndOptimizationGuideL4:
    pass


@dataclass
class ReferenceImplementationsL4:
    pass


@dataclass
class ReferenceStackMinimalL4:
    pass


@dataclass
class ReleaseEvidenceAssemblerL4:
    pass


@dataclass
class RepoLayoutAndInterfacesL4:
    pass


@dataclass
class ResearchExtensionsRoadmapL4:
    pass


@dataclass
class RuntimeStateMachineReferenceL4:
    pass


@dataclass
class SchemaEvolutionPlaybookL4:
    pass


@dataclass
class ScopeAndNonGoalsL4:
    pass


@dataclass
class SDKUsageGuideL4:
    pass


@dataclass
class SecurityCaseTemplateL4:
    pass


@dataclass
class SecurityCodingChecklistL4:
    pass


@dataclass
class SpecLintImplementationL4:
    pass


@dataclass
class SpecLintRulesL4:
    pass


@dataclass
class SREIncidentTriagePlaybookL4:
    pass


@dataclass
class TestHarnessImplementationL4:
    pass


@dataclass
class ThirdPartyOperatorCertificationProgramL4:
    pass


@dataclass
class ThreatModelAndControlCrosswalkL4:
    pass


@dataclass
class ToolingAndAutomationSuiteL4:
    pass


@dataclass
class ToolingSuiteL4:
    pass
